Repository OurMenu/OurMenu-Android-V2, pull requests merged in 2025-08, with the labels that each got.

#79 [Feat] Firebase , CI/CD 추가
  .github/workflows/android-ci.yml
  .github/workflows/firebase-app-distribution-debug.yml
  .gitignore
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 📄 docs, ✨ feat

#77 [FEAT] 메뉴판 삭제, 순서변경 Api 구현
  app/src/main/java/com/kuit/ourmenu/data/model/menuFolder/request/MenuFolderIndexRequest.kt
  app/src/main/java/com/kuit/ourmenu/data/repository/MenuFolderRepository.kt
  app/src/main/java/com/kuit/ourmenu/data/service/MenuFolderService.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/component/DeleteMenuFolderModal.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/component/MenuFolderButton.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/navigation/MenuFolderNavigation.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/screen/MenuFolderScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/viewmodel/MenuFolderViewModel.kt
  app/src/main/java/com/kuit/ourmenu/ui/navigator/MainNavHost.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/screen/LandingScreen.kt
  app/src/main/java/com/kuit/ourmenu/utils/dragndrop/DragAndDropListState.kt
  app/src/main/java/com/kuit/ourmenu/utils/dragndrop/Ext.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feat, 🐶 익성, 👌 OK Merge

#81 [FEAT] home api 연결
  .gitignore
  app/src/main/java/com/kuit/ourmenu/data/di/ServiceModule.kt
  app/src/main/java/com/kuit/ourmenu/data/model/home/request/HomeAnswerRequest.kt
  app/src/main/java/com/kuit/ourmenu/data/model/home/response/HomeQuestionResponse.kt
  app/src/main/java/com/kuit/ourmenu/data/model/home/response/HomeResponse.kt
  app/src/main/java/com/kuit/ourmenu/data/repository/HomeRepository.kt
  app/src/main/java/com/kuit/ourmenu/data/service/HomeService.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/dialog/DialogBigButton.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/topappbar/OurMenuAddButtonTopAppBar.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/dialog/HomeDialog.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/dialog/HomeDialogAssets.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/main/HomeMainRecommendation.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/main/HomeMainRecommendationItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/main/HomeMainRecommendationList.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/main/HomeMainRecommendationText.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/sub/HomeSubRecommendation.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/sub/HomeSubRecommendationItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/sub/HomeSubRecommendationList.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/sub/HomeSubRecommendationText.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/dummy/HomeDummyData.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/kuit/ourmenu/ui/navigator/MainNavHost.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feat, 🧸 나은, 👌 OK Merge
