Repository OurMenu/OurMenu-Android-V2, pull requests merged in 2025-01, with the labels that each got.

#12 [docs]: android.yml 파일 생성 (#11)
  .github/workflows/android.yml
Labels: documentation

#19 [init] 폰트, 컬러 설정하기
  .idea/.name
  .idea/appInsightsSettings.xml
  .idea/compiler.xml
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  app/src/main/java/com/kuit/ourmenu/ui/theme/Color.kt
  app/src/main/java/com/kuit/ourmenu/ui/theme/Theme.kt
  app/src/main/java/com/kuit/ourmenu/ui/theme/Type.kt
  app/src/main/res/font/black.ttf
  app/src/main/res/font/bold.ttf
  app/src/main/res/font/extrabold.ttf
  app/src/main/res/font/extralight.ttf
  app/src/main/res/font/light.ttf
  app/src/main/res/font/medium.ttf
  app/src/main/res/font/regular.ttf
  app/src/main/res/font/semibold.ttf
  app/src/main/res/font/thin.ttf
Labels: 🎨 ui

#20 [ui]: 홈 UI 구현 #13
  app/src/main/java/com/kuit/ourmenu/ui/common/OurMenuLogoTopAppBarWithAddButton.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/dialog/DialogBigButton.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/dialog/HomeDialog.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/dialog/HomeDialogAssets.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/dialog/HomeDialogTouchBox.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/main/HomeMainRecommendation.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/main/HomeMainRecommendationItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/main/HomeMainRecommendationList.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/main/HomeMainRecommendationText.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/sub/HomeSubRecommendation.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/sub/HomeSubRecommendationItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/sub/HomeSubRecommendationList.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/component/recommendation/sub/HomeSubRecommendationText.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/dummy/HomeDummyData.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/theme/Type.kt
  app/src/main/res/drawable/ic_close_24_n400.xml
  app/src/main/res/drawable/ic_home_dialog_touch.xml
  app/src/main/res/drawable/ic_home_plus.xml
  app/src/main/res/drawable/ic_home_reco_1.png
  app/src/main/res/drawable/ic_home_sub_reco_1.png
  app/src/main/res/drawable/ic_ourmenu_text_logo.xml
  app/src/main/res/drawable/img_home_popup_thumbsup.png
  app/src/main/res/drawable/img_popup_dice.png
Labels: 🎨 ui, 🐶 익성

#25 [UI] Menu Info 화면 구현 (#23)
  app/build.gradle.kts
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/screen/AddMenuInfoScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/screen/AddMenuScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/screen/AddMenuSearchScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/screen/AddMenuTagScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/GoToMapButton.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/bottomsheet/BottomSheetDragHandle.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/chip/MenuFolderChip.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/chip/TagChip.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/topappbar/OurMenuAddButtonTopAppBar.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/topappbar/OurMenuBackButtonTopAppBar.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/component/info/MenuInfoAdditionalContent.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/component/info/MenuInfoChipContent.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/component/info/MenuInfoContent.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/component/info/MenuInfoFolderChipGrid.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/component/info/MenuInfoImagePager.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/component/info/MenuInfoMapButton.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/component/info/MenuInfoTagChipGrid.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/component/info/MenuInfoTopIcons.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/component/map/MenuInfoMapBottomSheetContent.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/component/map/MenuInfoMapContent.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/component/map/MenuInfoMapImage.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/component/map/MenuInfoMapTagContent.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/dummy/MenuInfoDummyData.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/screen/MenuInfoDefaultScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/screen/MenuInfoMapScreen.kt
  app/src/main/java/com/kuit/ourmenu/utils/ExtensionUtil.kt
  app/src/main/res/drawable/ic_menu_info_info_20.xml
  app/src/main/res/drawable/ic_menu_info_meno_20.xml
  app/src/main/res/drawable/ic_menu_info_nav_24.xml
  app/src/main/res/drawable/icon_vert_white_24.xml
  app/src/main/res/drawable/img_dummy_menu.png
  app/src/main/res/drawable/img_menu_folder_dummy.png
  app/src/main/res/values/strings.xml
Labels: 🎨 ui, 🐶 익성, 👌 OK Merge

#27 [FEAT, REFACTOR] : AddMenuScreen 기능 구현
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/AddMenuSearchBackground.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/bottomsheet/AddMenuBottomSheetContent.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/bottomsheet/IconSelectBottomSheet.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/bottomsheet/TagSelectBottomSheet.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/item/AddMenuInfoAddressFieldItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/item/AddMenuInfoMenuBoardFieldItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/item/AddMenuInfoTextFieldItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/item/FoodTagItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/item/IconItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/item/RestaurantSearchItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/item/SelectMenuItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/screen/AddMenuInfoScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/screen/AddMenuScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/screen/AddMenuSearchScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/screen/AddMenuTagScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/viewmodel/AddMenuSearchViewModel.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/BottomFullWidthButton.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/BottomHalfWidthButton.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/SearchBar.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/screen/LandingScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/screen/LoginScreen.kt
  gradle/libs.versions.toml
Labels: ✨ feat, ♻️ refactor, 🦦재우, 👌 OK Merge
