Repository OurMenu/OurMenu-Android-V2, pull requests merged in 2025-05, with the labels that each got.

#62 [REFACTOR] 온보딩 로직 단순화
  .idea/appInsightsSettings.xml
  app/src/main/java/com/kuit/ourmenu/ui/common/LoginTextField.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/topappbar/OnboardingTopAppBar.kt
  app/src/main/java/com/kuit/ourmenu/ui/navigator/MainNavController.kt
  app/src/main/java/com/kuit/ourmenu/ui/navigator/MainNavHost.kt
  app/src/main/java/com/kuit/ourmenu/ui/navigator/Routes.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/mapper/CacheInfoResponseMapper.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/model/LandingUiState.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/model/LoginUiState.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/model/MealTimeState.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/screen/LandingScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/screen/LoginScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/state/CacheState.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/viewmodel/LandingViewModel.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/viewmodel/LoginViewModel.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/viewmodel/SignupViewModel.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/viewmodel/SplashViewModel.kt
  app/src/main/java/com/kuit/ourmenu/ui/signup/component/EmailSpinner.kt
  app/src/main/java/com/kuit/ourmenu/ui/signup/component/MealTime.kt
  app/src/main/java/com/kuit/ourmenu/ui/signup/component/VerifyCodeTextField.kt
  app/src/main/java/com/kuit/ourmenu/ui/signup/model/PasswordState.kt
  app/src/main/java/com/kuit/ourmenu/ui/signup/model/SignupState.kt
  app/src/main/java/com/kuit/ourmenu/ui/signup/navigation/SignupNavigation.kt
  app/src/main/java/com/kuit/ourmenu/ui/signup/screen/SignupEmailScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/signup/screen/SignupMealTimeScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/signup/screen/SignupPasswordScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/signup/screen/SignupVerifyScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/signup/uistate/SignupUiState.kt
  app/src/main/java/com/kuit/ourmenu/ui/signup/viewmodel/SignupViewModel.kt
  app/src/main/java/com/kuit/ourmenu/utils/AnimationUtil.kt
Labels: ♻️ refactor, 🐶 익성

#63 [UI] mypage 완료
  app/src/main/java/com/kuit/ourmenu/ui/common/topappbar/OurMenuAddButtonTopAppBar.kt
  app/src/main/java/com/kuit/ourmenu/ui/my/component/DeleteAccountModal.kt
  app/src/main/java/com/kuit/ourmenu/ui/my/component/LogoutModal.kt
  app/src/main/java/com/kuit/ourmenu/ui/my/component/MyBottomModal.kt
  app/src/main/java/com/kuit/ourmenu/ui/my/component/MyCurrentPasswordModal.kt
  app/src/main/java/com/kuit/ourmenu/ui/my/component/MyMealTime.kt
  app/src/main/java/com/kuit/ourmenu/ui/my/component/MyNewPasswordModal.kt
  app/src/main/java/com/kuit/ourmenu/ui/my/screen/EditMyMealTimeScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/my/screen/MyScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/theme/Color.kt
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_clock.xml
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 ui, 🧸 나은

#66 [HOTFIX] 경로 바뀐 문제 해결
  app/src/main/java/com/kuit/ourmenu/ui/my/screen/EditMyMealTimeScreen.kt
Labels: ⚡️ fix, 🧸 나은
