Repository OurMenu/OurMenu-Android-V2, pull requests merged in 2025-02, with the labels that each got.

#31 [FEAT] navigation 사용환경 구축
  app/build.gradle.kts
  app/src/main/java/com/kuit/ourmenu/MainActivity.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/AddMenuAddImageComponent.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/item/AddMenuAddedImageItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/item/AddMenuInfoAddressFieldItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/item/AddMenuInfoMenuBoardFieldItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/item/AddMenuInfoTextFieldItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/screen/AddMenuInfoScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/navigator/MainNavGraph.kt
  app/src/main/java/com/kuit/ourmenu/ui/navigator/Routes.kt
  app/src/main/res/drawable/ic_addmenu_x.xml
  app/src/main/res/drawable/ic_dropdown_checked.xml
  app/src/main/res/drawable/ic_dropdown_unchecked.xml
  gradle/libs.versions.toml
Labels: ✨ feat

#33 [FEAT] Hilt 세팅 및 더미코드 작성 , Retrofit 의존성 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kuit/ourmenu/MainActivity.kt
  app/src/main/java/com/kuit/ourmenu/OurMenuApp.kt
  app/src/main/java/com/kuit/ourmenu/ui/dummy/data/DummyData.kt
  app/src/main/java/com/kuit/ourmenu/ui/dummy/data/DummyResponse.kt
  app/src/main/java/com/kuit/ourmenu/ui/dummy/di/NetworkModule.kt
  app/src/main/java/com/kuit/ourmenu/ui/dummy/di/RepositoryModule.kt
  app/src/main/java/com/kuit/ourmenu/ui/dummy/di/ServiceModule.kt
  app/src/main/java/com/kuit/ourmenu/ui/dummy/repository/DummyRepository.kt
  app/src/main/java/com/kuit/ourmenu/ui/dummy/service/DummyService.kt
  app/src/main/java/com/kuit/ourmenu/ui/dummy/viewmodel/DummyViewModel.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ✨ feat

#36 [FIX] 순환 의존성 오류 수정
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/kuit/ourmenu/di/NetworkModule.kt
  app/src/main/java/com/kuit/ourmenu/di/ServiceModule.kt
  app/src/main/java/com/kuit/ourmenu/dummy/data/DummyData.kt
  app/src/main/java/com/kuit/ourmenu/dummy/data/DummyResponse.kt
  app/src/main/java/com/kuit/ourmenu/dummy/repository/DummyRepository.kt
  app/src/main/java/com/kuit/ourmenu/dummy/service/DummyService.kt
  app/src/main/java/com/kuit/ourmenu/dummy/viewmodel/DummyViewModel.kt
  app/src/main/java/com/kuit/ourmenu/ui/dummy/di/RepositoryModule.kt
  app/src/main/java/com/kuit/ourmenu/ui/dummy/service/DummyService.kt
  app/src/main/java/com/kuit/ourmenu/ui/navigator/Routes.kt
  gradle/libs.versions.toml
Labels: ⚡️ fix, 🐶 익성

#40 [FEAT] Api 연결용 네트워크 셋업
  app/build.gradle.kts
  app/src/main/java/com/kuit/ourmenu/data/di/NetworkModule.kt
  app/src/main/java/com/kuit/ourmenu/data/di/ServiceModule.kt
  app/src/main/java/com/kuit/ourmenu/data/model/base/ApiResponseHandler.kt
  app/src/main/java/com/kuit/ourmenu/data/model/base/BaseResponse.kt
  app/src/main/java/com/kuit/ourmenu/data/model/dummy/request/DummyRequest.kt
  app/src/main/java/com/kuit/ourmenu/data/model/dummy/response/DummyResponse.kt
  app/src/main/java/com/kuit/ourmenu/data/repository/DummyRepository.kt
  app/src/main/java/com/kuit/ourmenu/data/service/DummyService.kt
  app/src/main/java/com/kuit/ourmenu/di/NetworkModule.kt
  app/src/main/java/com/kuit/ourmenu/dummy/data/DummyData.kt
  app/src/main/java/com/kuit/ourmenu/dummy/data/DummyResponse.kt
  app/src/main/java/com/kuit/ourmenu/dummy/repository/DummyRepository.kt
  app/src/main/java/com/kuit/ourmenu/dummy/service/DummyService.kt
  app/src/main/java/com/kuit/ourmenu/dummy/viewmodel/DummyViewModel.kt
  app/src/main/java/com/kuit/ourmenu/ui/dummy/DummyScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/dummy/state/DummyState.kt
  app/src/main/java/com/kuit/ourmenu/ui/dummy/viewmodel/DummyViewModel.kt
  gradle/libs.versions.toml
Labels: ✨ feat, 🐶 익성
