Repository OurMenu/OurMenu-Android-V2, pull requests merged in 2025-03, with the labels that each got.

#41 [UI] Signup 화면 일부 구현
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/component/EmailDropdown.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/component/EmailSpinner.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/component/LoginTextField.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/component/VerifyCodeTextField.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/screen/LoginScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/screen/signup/SignupPasswordScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/screen/signup/SignupVerifyScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/theme/Type.kt
  app/src/main/res/drawable/ic_dropdown_btn.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 ui, 🧸 나은

#42 [fix]: dummy 제거 및 baseResponse 수정
  app/src/main/java/com/kuit/ourmenu/data/model/base/ApiResponseHandler.kt
  app/src/main/java/com/kuit/ourmenu/di/RepositoryModule.kt
  app/src/main/java/com/kuit/ourmenu/dummy/repositoryimpl/DummyRepositoryImpl.kt
Labels: ⚡️ fix, 🐶 익성

#47 [FEAT] AddMenu에서 태그/아이콘 추가 화면 구현, TokenManager 구현
  .idea/deploymentTargetSelector.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/kuit/ourmenu/data/di/NetworkModule.kt
  app/src/main/java/com/kuit/ourmenu/data/di/RepositoryModule.kt
  app/src/main/java/com/kuit/ourmenu/data/di/ServiceModule.kt
  app/src/main/java/com/kuit/ourmenu/data/model/auth/request/LoginRequest.kt
  app/src/main/java/com/kuit/ourmenu/data/model/auth/response/LoginResponse.kt
  app/src/main/java/com/kuit/ourmenu/data/model/auth/response/TokenReIssueResponse.kt
  app/src/main/java/com/kuit/ourmenu/data/repository/AuthRepository.kt
  app/src/main/java/com/kuit/ourmenu/data/repository/DummyRepository.kt
  app/src/main/java/com/kuit/ourmenu/data/service/AuthService.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/SelectedTagGroup.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/bottomsheet/IconSelectBottomSheet.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/bottomsheet/TagSelectBottomSheet.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/item/AddMenuInfoMenuBoardFieldItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/item/IconItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/item/SelectedTagItem.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/screen/AddMenuTagScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/IconItemGroup.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/chip/TagChipGroup.kt
  app/src/main/java/com/kuit/ourmenu/ui/onboarding/viewmodel/LoginViewModel.kt
  app/src/main/java/com/kuit/ourmenu/utils/auth/AuthInterceptor.kt
  app/src/main/java/com/kuit/ourmenu/utils/auth/TokenAuthenticator.kt
  app/src/main/java/com/kuit/ourmenu/utils/auth/TokenManager.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ✨ feat, 🎨 ui, 🦦재우, 👌 OK Merge

#49 [UI] 메뉴판 화면 구현
  app/src/main/java/com/kuit/ourmenu/ui/common/topappbar/BackButtonTopAppBar.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/component/AddButton.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/component/MenuFolderButton.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/component/MenuFolderMenuButton.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/component/MenuFolderTopAppBar.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/screen/MenuFolderAllMenuScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/screen/MenuFolderDetailScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/screen/MenuFolderScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/theme/Type.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_dropdown_btn.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_filter.xml
  app/src/main/res/drawable/ic_kebab.xml
  app/src/main/res/drawable/ic_my_menu_title.xml
  app/src/main/res/drawable/ic_to_map.xml
  app/src/main/res/drawable/ic_trashcan.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 ui, 🧸 나은

#53 [FEAT] 메뉴판 Api 구현
  app/build.gradle.kts
  app/src/main/java/com/kuit/ourmenu/data/di/ServiceModule.kt
  app/src/main/java/com/kuit/ourmenu/data/model/menuFolder/response/MenuFolderIconType.kt
  app/src/main/java/com/kuit/ourmenu/data/model/menuFolder/response/MenuFolderResponse.kt
  app/src/main/java/com/kuit/ourmenu/data/repository/MenuFolderRepository.kt
  app/src/main/java/com/kuit/ourmenu/data/service/MenuFolderService.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/component/bottomsheet/TagSelectBottomSheet.kt
  app/src/main/java/com/kuit/ourmenu/ui/addmenu/screen/AddMenuScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/chip/TagChipGroup.kt
  app/src/main/java/com/kuit/ourmenu/ui/common/topappbar/BackButtonTopAppBar.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/component/FilterBottomSheet.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/component/MenuFolderButton.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/component/MenuFolderMenuButton.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/component/MenuFolderTopAppBar.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/component/SortDropdown.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/screen/MenuFolderAllMenuScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/screen/MenuFolderDetailScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/screen/MenuFolderScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuFolder/viewmodel/MenuFolderViewModel.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/screen/MenuInfoDefaultScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/menuinfo/screen/MenuInfoMapScreen.kt
  app/src/main/java/com/kuit/ourmenu/ui/navigator/MainNavGraph.kt
  app/src/main/java/com/kuit/ourmenu/ui/navigator/Routes.kt
  app/src/main/res/drawable/ic_dropdown_btn_up.xml
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: 🩹 chore, ✨ feat, ⚡️ fix, ♻️ refactor, 🎨 ui, 🧸 나은
